name: docker-build

on:
  push:
    branches: [release, develop]

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build staging container
        run: docker build -t deveote/zapplayer-be:develop .
        if: contains('refs/heads/develop',github.ref)
      - name: Build production container
        run: docker build -t deveote/zapplayer-be:release .
        if: contains('refs/heads/release',github.ref)
      - name: Reload containers
        run: docker-compose -f /docker/compose/docker-compose.yml up -d


